language: lua

addons:
  apt:
    update: true
    packages:
      - lua5.2
      - lua-filesystem

script:
  - git clone --recursive https://github.com/shagu/webls.git .webls
  - cp -f .webls-config.lua .webls/config.lua || true
  - rm -r .webls/content
  - cp -r content .webls/content
  - ( cd .webls && ./webls.lua )
  - mv .webls/www public

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: public
